void ver_comandos();
void cambiar_n(int *i, int n);
void llenar(float datos[], int n);
void imprimir(float datos[], int n);
float media(float datos[], int n);
float mediana(float datos[], int n);
float moda(float datos[], int n);
float rango(float datos[], int n);
float varianza(float datos[], int n);
float des_estandar(float datos[], int n);
float cuartil_1(float datos[], int n);
float cuartil_3(float datos[], int n);
float rango_intercuartil(float datos[], int n);
void todo(float datos[], int n);
void ordenamiento(float datos[], int n);